repos:
- repo: local
  hooks:
  - id: lint-python
    name: Check source files
    entry: "pants lint check ::"
    language: script
    types: [python]
    pass_filenames: false
    verbose: true

  - id: test-python
    name: Run tests
    entry: "pants test ::"
    language: script
    types: [python]
    pass_filenames: false
    verbose: true

  - id: lint-build-files
    name: Check BUILD files
    entry: "pants update-build-files --check ::"
    language: script
    files: BUILD
    pass_filenames: false
    verbose: true
